sudo: false

language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Lint
      script:
        - yarn lint
    - stage: Prettier
      script:
        - yarn prettier:check
    - stage: Build
      if: branch != master
      script:
        - yarn build
    - stage: Build & Package
      if: branch = master
      os: osx
      osx_image: xcode10.1
      script:
        - yarn build
        - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x ./scripts/add-osx-cert.sh; fi
        - if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/add-osx-cert.sh; fi
        - yarn package
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine

before_deploy:
  - export TRAVIS_TAG="preview"

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  draft: true
  overwrite: true
  file_glob: true
  file:
    - release/*.dmg
    - release/*-mac.zip
