sudo: false

language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Quality
      script:
        - yarn lint
      name: Lint
    - script:
        - yarn prettier:check
      name: Prettier
    - stage: Build
      if: branch != master
      script:
        - yarn build
      name: Build
    - stage: Build & Package
      if: branch = master
      os: osx
      osx_image: xcode10.1
      script:
        - yarn clean
      name: Clean
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - script:
        - yarn build
      name: Build
    - script:
        - yarn package-and-publish
      name: Package & Publish
