sudo: false

language: node_js
node_js: "10.16.3"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Lint
      script:
        - yarn lint
    - stage: Release and Publish
      os: osx
      osx_image: xcode10.1
      script:
        - yarn dist
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
